apiVersion: v1
kind: Pod
metadata:
  labels:
    app_name: mongo
  name: mongo
  namespace: default
spec:
  containers:
  - image: bitnami/mongodb:latest
    imagePullPolicy: IfNotPresent
    name: mongo
    ports:
    - containerPort: 27017
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 40Gi
      requests:
        cpu: "1"
        memory: 40Gi
    volumeMounts:
    - mountPath: /bitnami
      name: data
  dnsPolicy: ClusterFirst
  securityContext:
    supplementalGroups:
    - 65534
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: mongo-pvc
