apiVersion: v1
kind: Pod
metadata:
  labels:
    app_name: nerserver
  name: nerserver
  namespace: default
spec:
  containers:
  - image: nerproject:latest
    imagePullPolicy: IfNotPresent
    name: nerserver
    args:
    - -f
    - /dev/null
    command:
    - tail
    ports:
    - containerPort: 5000
      protocol: TCP
    volumeMounts:
    - mountPath: /opt/app/nerproject/shared-pvc
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: shared-pvc

