apiVersion: v1
kind: Service
metadata:
  labels:
    app_name: mongo
  name: mongo
  namespace: default
spec:
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app_name: mongo
  type: NodePort
