apiVersion: v1
kind: Pod
metadata:
  labels:
    app_name: mongo
  name: mongo
  namespace: default
spec:
  hostNetwork: true
  containers:
  - image: bitnami/mongodb:latest
    imagePullPolicy: IfNotPresent
    name: mongo
    ports:
    - containerPort: 27017
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
    volumeMounts:
    - mountPath: /bitnami
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: mongo-pvc
